apiVersion: v1
kind: Pod
metadata:
  name: jose-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:

    - name: nginx-with-html
      image: jriosor/webserver:4.0
      env:
      - name: LOG_HANDLERS
        value: file
      volumeMounts:
      - mountPath: /log
        name: log-volume

  volumes:
    - name: log-volume
      hostPath:
        # directory location on host
        path: /Users/Jose/Desktop/CKA Certification/data
        # this field is optional
        type: Directory
  imagePullSecrets:
    - name: jose-secret
