apiVersion: apps/v1
kind: Deployment
metadata:
  name: adidas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adidas
  template:
    metadata:
      labels:
        app: adidas
    spec:
      containers:
      - name: adidas
        image: jriosor/adidas:4.0
        ports:
        - containerPort: 3000
